spring:
  application:
    name: ZuulMicroservice
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
instance:
  hostname: localhost
  
server:
  port: 8989
  
zuul:
  prefix: /demo
  routes:
    bankingService:
      path: /bank/**
      service-id: BANKSERVICE
    transactionService:
      path: /transaction/**
      service-id: TRANSACTIONSERVICE
     
     
      